name: asciidoctor-ghpages

on:
  push:
    branches:
      - 'main'
    paths:
      - asciidocs/**

jobs:
  build:
    name: Build & Publish 🚀
    runs-on: ubuntu-latest
    env:
      INPUTPATH: asciidocs
      OUTPUTPATH: asciidocs
      SLIDES: false
      BRANCH: gh-pages
    steps:
      - uses: actions/checkout@v2
      - name: converting
        run: convert.sh
        shell: bash
        with:
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: Build
        uses: quirinecker/asciidoctor-convert-action@main
        with:
          slides: ${{ env.SLIDES }}
          inputPath: ${{ env.INPUTPATH }}
          outputPath: ${{ env.OUTPUTPATH }}
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ github.TOKEN }}
          BRANCH: ${{ env.BRANCH }}
          FOLDER: ${{ env.OUTPUTPATH }}